### ISSUE TITLE
Apicast Deploy on namespace different from 3Scale API Manager doesn't work

### ISSUE THREAD

**Issue by raffamendes** [3scale/apicast-operator#72]
Hi,

I'm trying to deploy a apicast on an different namespace from the apimanager.
When deploying using the template all I had to do was configure the BACKEND_ENDPOINT_OVERRIDE variable in the deploymentconfig for it to work.

Is there a way to do the same configuration on the apicast deployed using the operator?

I had no luck make this to work.

I'm using CRC 4.3 and 3Scale 2.8

the cr used to create the apicast
```yaml
---
apiVersion: apps.3scale.net/v1alpha1
kind: APIcast
metadata:
  name: apicast-user1-tenant
spec:
  deploymentEnvironment: staging
  logLevel: debug
  adminPortalCredentialsRef:
    name: 3scaleportal
```

the 3scaleportal secret:
```code
oc create secret generic 3scaleportal --from-literal=AdminPortalURL=https://25fa1ea64bd38c22c05b9d410d13836d3fff16619446354fb924c6a0d407a403@user1-tenant-admin.apps-crc.testing 
```
